solidus_backend-1.3.0/config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :dashboards, only: [] do
      collection do
        get :home
      end
    end

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
      resources :promotion_codes, only: [:index]
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :variant_property_rule_values, only: [:destroy] do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
      resources :prices, only: [:destroy, :index, :edit, :update, :new, :create]
    end
    get '/products/:product_slug/stock', to: "stock_items#index", as: :product_stock

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :properties_child do
      collection do
        #get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        put :advance
        get :confirm
        put :complete
        post :resend
        get "/adjustments/unfinalize", to: "orders#unfinalize_adjustments"
        get "/adjustments/finalize", to: "orders#finalize_adjustments"
        put :approve
        put :cancel
        put :resume
      end

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments, only: [:index, :new, :show, :create] do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end

      resources :cancellations, only: [:index] do
        collection do
          post :short_ship
        end
      end
    end

    resource :general_settings, only: [:edit, :update] do
      collection do
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :adjustment_reasons, except: [:show, :destroy]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories

    resources :stock_transfers, except: [:destroy] do
      member do
        get :receive
        put :finalize
        put :close
        get :tracking_info
        put :ship
      end
    end

    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
        post :update_positions
      end
    end

    resources :stock_items, except: [:show, :new, :edit]
    resources :tax_rates

    resources :trackers
    resources :payment_methods do
      collection do
        post :update_positions
      end
    end

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
      resources :store_credits, except: [:destroy] do
        member do
          get :edit_amount
          put :update_amount
          get :edit_validity
          put :invalidate
        end
      end
    end

    resources :style_guide, only: [:index]
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

solidus_backend-1.3.0/app/controllers/spree/admin/zones_controller.rb
module Spree
  module Admin
    class ZonesController < ResourceController
      before_action :load_data, except: :index

      def new
        @zone.zone_members.build
      end

      private

      def collection
        params[:q] ||= {}
        params[:q][:s] ||= "name asc"
        @search = super.ransack(params[:q])
        @zones = @search.result.page(params[:page]).per(params[:per_page])
      end

      def load_data
        @countries = Country.order(:name)
        @states = State.order(:name)
        @zones = Zone.order(:name)
      end
    end
  end
end

solidus_backend-1.3.0/app/views/spree/admin/zones/_country_members.html.erb
<div id="country_members" data-hook="member" class="omega six columns">
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree::Country.model_name.human(count: :other) %></legend>

    <%= zone_form.field_container :country_ids do %>
      <%= zone_form.label :country_ids, Spree::Country.model_name.human(count: :other) %><br>
      <%= zone_form.collection_select :country_ids, @countries, :id, :name, {}, { :multiple => true, :class => "select2 fullwidth" } %>
    <% end %>
  </fieldset>
</div>

solidus_backend-1.3.0/app/views/spree/admin/zones/_form.html.erb
<div class="alpha six columns" data-hook="admin_zone_form_fields">
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree.t(:general_settings)%></legend>

    <%= zone_form.field_container :name do %>
      <%= zone_form.label :name %><br />
      <%= zone_form.text_field :name, :class => 'fullwidth' %>
    <% end %>

    <%= zone_form.field_container :description do %>
      <%= zone_form.label :description %><br />
      <%= zone_form.text_field :description, :class => 'fullwidth' %>
    <% end %>

    <div data-hook="default" class="field">
      <%= zone_form.check_box :default_tax %>
      <%= zone_form.label :default_tax %>
    </div>

    <div data-hook="type" class="field">
      <%= label_tag Spree.t(:type) %>
      <ul>
        <li>
          <%= zone_form.radio_button('kind', 'country', { :id => 'country_based' }) %>
          <%= label_tag :country_based, Spree.t(:country_based) %>
        </li>
        <li>
          <%= zone_form.radio_button('kind', 'state', { :id => 'state_based' }) %>
          <%= label_tag :state_based, Spree.t(:state_based) %>
        </li>
      </ul>
    </div>
  </fieldset>
</div>

<%= render :partial => 'state_members', :locals => { :zone_form => zone_form }%>
<%= render :partial => 'country_members', :locals => { :zone_form => zone_form } %>

solidus_backend-1.3.0/app/views/spree/admin/zones/_state_members.html.erb
<div id="state_members" data-hook="member" class="omega six columns">
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree::State.model_name.human(count: :other) %></legend>

    <%= zone_form.field_container :state_ids do %>
      <%= zone_form.label :state_ids, Spree::State.model_name.human(count: :other) %><br>
      <%= zone_form.collection_select :state_ids, @states, :id, :name, {}, { :multiple => true, :class => "select2 fullwidth" } %>
    <% end %>
  </fieldset>
</div>

solidus_backend-1.3.0/app/views/spree/admin/zones/edit.html.erb
<%= render 'spree/admin/shared/areas_tabs' %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_zone) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_zones_list), admin_zones_path, :icon => 'arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @zone } %>

<%= form_for [:admin, @zone] do |zone_form| %>
  <%= render :partial => 'form', :locals => { :zone_form => zone_form } %>
  <div class="clear"></div>
  <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
<% end %>

solidus_backend-1.3.0/app/views/spree/admin/zones/index.html.erb
<%= render 'spree/admin/shared/areas_tabs' %>

<% content_for :page_title do %>
  <%= Spree::Zone.model_name.human(count: :other) %>
<% end %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::Zone) %>
    <li>
      <%= button_link_to Spree.t(:new_zone), new_object_url, :icon => 'plus', :id => 'admin_new_zone_link' %>
    </li>
  <% end %>
<% end %>

<%= paginate @zones, theme: "solidus_admin" %>

<% if @zones.any? %>
  <table class="index" id='listing_zones' data-hook>
    <colgroup>
      <col style="width: 30%" />
      <col style="width: 40%" />
      <col style="width: 15%" />
      <col style="width: 15%" />
    </colgroup>
    <thead>
      <tr data-hook="zones_header">
        <th><%= sort_link @search,:name, Spree::Zone.human_attribute_name(:name), :title => 'zones_order_by_name_title' %></th>
        <th>
          <%= sort_link @search,:description, Spree::Zone.human_attribute_name(:description), {}, {:title => 'zones_order_by_description_title'} %>
        </th>
        <th><%= Spree.t(:default_tax) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @zones.each do |zone| %>
        <tr id="<%= spree_dom_id zone %>" data-hook="zones_row" class="<%= cycle('odd', 'even')%>">
          <td class="align-center"><%= zone.name %></td>
          <td><%= zone.description %></td>
          <td class="align-center"><%= zone.default_tax? ? Spree.t(:say_yes) : Spree.t(:say_no) %></td>
          <td class="actions">
            <% if can?(:update, zone) %>
              <%= link_to_edit zone, :no_text => true %>
            <% end %>
            <% if can?(:destroy, zone) %>
              <%= link_to_delete zone, :no_text => true %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::Zone,
                 new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @zones, theme: "solidus_admin" %>

solidus_backend-1.3.0/app/views/spree/admin/zones/new.html.erb
<%= render 'spree/admin/shared/areas_tabs' %>

<% content_for :page_title do %>
  <%= Spree.t(:new_zone) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_zones_list), spree.admin_zones_path, :icon => 'arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @zone } %>

<%= form_for [:admin, @zone] do |zone_form| %>
  <%= render :partial => 'form', :locals => { :zone_form => zone_form } %>

  <div class="clear"></div>
  
  <%= render :partial => 'spree/admin/shared/new_resource_links' %>
<% end %>