solidus_backend-1.3.0/config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :dashboards, only: [] do
      collection do
        get :home
      end
    end

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
      resources :promotion_codes, only: [:index]
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :variant_property_rule_values, only: [:destroy] do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
      resources :prices, only: [:destroy, :index, :edit, :update, :new, :create]
    end
    get '/products/:product_slug/stock', to: "stock_items#index", as: :product_stock

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :properties_child do
      collection do
        #get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        put :advance
        get :confirm
        put :complete
        post :resend
        get "/adjustments/unfinalize", to: "orders#unfinalize_adjustments"
        get "/adjustments/finalize", to: "orders#finalize_adjustments"
        put :approve
        put :cancel
        put :resume
      end

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments, only: [:index, :new, :show, :create] do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end

      resources :cancellations, only: [:index] do
        collection do
          post :short_ship
        end
      end
    end

    resource :general_settings, only: [:edit, :update] do
      collection do
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :adjustment_reasons, except: [:show, :destroy]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories

    resources :stock_transfers, except: [:destroy] do
      member do
        get :receive
        put :finalize
        put :close
        get :tracking_info
        put :ship
      end
    end

    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
        post :update_positions
      end
    end

    resources :stock_items, except: [:show, :new, :edit]
    resources :tax_rates

    resources :trackers
    resources :payment_methods do
      collection do
        post :update_positions
      end
    end

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
      resources :store_credits, except: [:destroy] do
        member do
          get :edit_amount
          put :update_amount
          get :edit_validity
          put :invalidate
        end
      end
    end

    resources :style_guide, only: [:index]
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

solidus_backend-1.3.0/app/controllers/spree/admin/customer_returns_controller.rb
module Spree
  module Admin
    class CustomerReturnsController < ResourceController
      belongs_to 'spree/order', find_by: :number

      before_action :parent # ensure order gets loaded to support our pseudo parent-child relationship
      before_action :load_form_data, only: [:new, :edit]
      before_action :build_return_items_from_params, only: [:create]
      create.fails  :load_form_data

      def edit
        @pending_return_items = @customer_return.return_items.select(&:pending?)
        @accepted_return_items = @customer_return.return_items.select(&:accepted?)
        @rejected_return_items = @customer_return.return_items.select(&:rejected?)
        @manual_intervention_return_items = @customer_return.return_items.select(&:manual_intervention_required?)
        @pending_reimbursements = @customer_return.reimbursements.select(&:pending?)

        super
      end

      private

      def location_after_save
        url_for([:edit, :admin, @order, @customer_return])
      end

      def build_resource
        Spree::CustomerReturn.new
      end

      def find_resource
        Spree::CustomerReturn.accessible_by(current_ability, :read).find(params[:id])
      end

      def collection
        parent # trigger loading the order
        @collection ||= Spree::ReturnItem
          .accessible_by(current_ability, :read)
          .where(inventory_unit_id: @order.inventory_units.pluck(:id))
          .map(&:customer_return).uniq.compact
        @customer_returns = @collection
      end

      def load_form_data
        return_items = @order.inventory_units.map(&:current_or_new_return_item).reject(&:customer_return_id)
        @rma_return_items, @new_return_items = return_items.partition(&:return_authorization_id)
        load_return_reasons
      end

      def load_return_reasons
        @reasons = Spree::ReturnReason.reasons_for_return_items(@customer_return.return_items)
      end

      def permitted_resource_params
        @permitted_resource_params ||= params.require('customer_return').permit(permitted_customer_return_attributes)
      end

      def build_return_items_from_params
        return_items_params = permitted_resource_params.delete(:return_items_attributes).values

        @customer_return.return_items = return_items_params.map do |item_params|
          next unless item_params.delete('returned') == '1'
          return_item = item_params[:id] ? Spree::ReturnItem.find(item_params[:id]) : Spree::ReturnItem.new
          return_item.assign_attributes(item_params)
          if item_params[:reception_status_event].blank?
            return redirect_to(new_object_url, flash: { error: 'Reception status choice required' })
          end
          return_item
        end.compact
      end
    end
  end
end

solidus_backend-1.3.0/app/helpers/spree/admin/customer_returns_helper.rb
module Spree
  module Admin
    module CustomerReturnsHelper
      def reimbursement_types
        @reimbursement_types ||= Spree::ReimbursementType.accessible_by(current_ability, :read).active
      end
    end
  end
end

solidus_backend-1.3.0/app/views/spree/admin/customer_returns/_reimbursements_table.html.erb
<table class="index customer-return-reimbursements">
  <thead data-hook="customer_return_header">
    <tr>
      <th><%= Spree::Reimbursement.human_attribute_name(:number) %></th>
      <th><%= Spree::Reimbursement.human_attribute_name(:total) %></th>
      <th><%= Spree::Reimbursement.human_attribute_name(:reimbursement_status) %></th>
      <th><%= Spree::Reimbursement.human_attribute_name(:created_at) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% reimbursements.each do |reimbursement| %>
      <tr id="<%= spree_dom_id(reimbursement) %>" data-hook="reimbursement_row" class="<%= cycle('odd', 'even')%>">
        <td>
          <% if reimbursement.reimbursed? %>
            <%= link_to reimbursement.number, url_for([:admin, @order, reimbursement]) %>
          <% else %>
            <%= reimbursement.number %>
          <% end %>
        </td>
        <td><%= reimbursement.display_total %></td>
        <td>
          <span class="state <%= reimbursement_status_color(reimbursement) %>">
            <%= reimbursement.reimbursement_status %>
          </span>
        </td>
        <td><%= pretty_time(reimbursement.created_at) %></td>
        <td class="actions">
          <% if !reimbursement.reimbursed? %>
            <%= link_to_edit_url url_for([:edit, :admin, @order, reimbursement]), title: "admin_edit_#{dom_id(reimbursement)}", no_text: true %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

solidus_backend-1.3.0/app/views/spree/admin/customer_returns/_return_item_decision.html.erb
<table class="show return-items-table">
  <thead>
    <tr>
      <th><%= Spree::Product.model_name.human %></th>
      <th><%= Spree::Variant.human_attribute_name(:sku) %></th>
      <th><%= Spree::ReturnItem.human_attribute_name(:amount) %></th>
      <th><%= Spree::ReturnItem.human_attribute_name(:preferred_reimbursement_type) %></th>
      <th><%= Spree::ReturnItem.human_attribute_name(:exchange_variant) %></th>
      <th><%= Spree::ReturnItem.human_attribute_name(:acceptance_status_errors) %></th>
      <th><%= Spree::ReturnItem.human_attribute_name(:reception_status) %></th>
      <% unless return_items.all?(&:received?)%>
        <th><%= Spree::ReturnItem.human_attribute_name(:item_received?) %></th>
      <% end %>
      <% if show_decision %>
        <th class="actions"></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% return_items.each do |return_item| %>
      <tr>
        <td>
          <div class="variant-name"><%= return_item.inventory_unit.variant.name %></div>
          <div class="variant-options"><%= return_item.inventory_unit.variant.options_text %></div>
        </td>
        <td>
          <%= return_item.inventory_unit.variant.sku %>
        </td>
        <td class="align-center">
          <%= return_item.display_amount %>
        </td>
        <td class="align-center">
          <%= reimbursement_type_name(return_item.preferred_reimbursement_type) %>
        </td>
        <td class="align-center">
          <%= return_item.exchange_variant.try(:exchange_name) %>
        </td>
        <td class="align-center">
          <%= return_item.acceptance_status_errors %>
        </td>
        <td class-"align-center">
          <%= return_item.reception_status.humanize %>
        </td>
        <% unless return_item.received? %>
          <td class='align-center'>
            <%= form_for [:admin, return_item] do |f| %>
              <%= f.hidden_field 'reception_status_event', value: 'receive' %>
              <%= f.button Spree.t('actions.receive'), class: 'fa icon_link no-text with-tip', "data-action" => 'save' %>
            <% end %>
          </td>
        <% end %>
        <% if show_decision %>
          <td class='actions'>
            <%= button_to [:admin, return_item], { class: 'fa fa-thumbs-up icon_link no-text with-tip', params: { "return_item[acceptance_status]" => 'accepted' }, "data-action" => 'save', title: Spree.t(:accept), method: 'put' } do %>
              <%= Spree.t(:accept) %>
            <% end %>
            <%= button_to [:admin, return_item], { class: 'fa fa-thumbs-down icon_link no-text with-tip', params: { "return_item[acceptance_status]" => 'rejected' }, "data-action" => 'remove', title: Spree.t(:reject), method: 'put' } do %>
              <%= Spree.t(:reject) %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

solidus_backend-1.3.0/app/views/spree/admin/customer_returns/_return_item_selection.html.erb
<table class="index return-items-table">
  <thead>
    <tr>
      <th>
        <%= check_box_tag 'select-all' %>
      </th>
      <th><%= Spree::Product.model_name.human %></th>
      <th><%= Spree::Variant.human_attribute_name(:sku) %></th>
      <th><%= Spree::ReturnItem.human_attribute_name(:amount) %></th>
      <th><%= Spree::ReturnItem.human_attribute_name(:inventory_unit_state) %></th>
      <th><%= Spree::ReturnItem.human_attribute_name(:exchange_variant) %></th>
      <th><%= Spree::ReturnItem.human_attribute_name(:resellable) %></th>
      <th><%= Spree::ReturnItem.human_attribute_name(:reception_status) %></th>
      <th><%= Spree::ReturnItem.human_attribute_name(:return_reason) %></th>
    </tr>
  </thead>
  <tbody>
    <%= f.fields_for :return_items, return_items do |item_fields| %>
      <% return_item = item_fields.object %>

      <tr>
        <td class="align-center inventory-unit-checkbox">
          <div style="display:none">
            <%= item_fields.hidden_field :inventory_unit_id %>
            <%= item_fields.hidden_field :return_authorization_id %>
            <%= item_fields.hidden_field :amount %>
          </div>
          <%= item_fields.check_box :returned, {checked: false, class: 'add-item', "data-price" => return_item.amount}, '1', '0' %>
        </td>
        <td>
          <div class="variant-name"><%= return_item.inventory_unit.variant.name %></div>
          <div class="variant-options"><%= return_item.inventory_unit.variant.options_text %></div>
        </td>
        <td>
          <%= return_item.inventory_unit.variant.sku %>
        </td>
        <td class="align-center">
          <%= return_item.display_amount %>
        </td>
        <td class="align-center">
          <%= return_item.inventory_unit.state %>
        </td>
        <td class="align-center">
          <%= return_item.exchange_variant.try(:exchange_name) %>
        </td>
        <td class="align-center">
          <%= item_fields.check_box :resellable, { checked: return_item.resellable } %>
        </td>
        <td class="align-center">
          <%= item_fields.select :reception_status_event, return_item.potential_reception_transitions, {include_blank: true}, {class: 'add-item select2 fullwidth'} %>
        </td>
        <td class="align-center">
          <%= item_fields.select :return_reason_id, @reasons.collect{|r|[r.name, r.id]}, {include_blank: true}, {class: 'select2 fullwidth'} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

solidus_backend-1.3.0/app/views/spree/admin/customer_returns/edit.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Customer Returns' } %>

<% content_for :page_title do %>
  <i class="fa fa-arrow-right"></i> <%= Spree::CustomerReturn.model_name.human %> #<%= @customer_return.number %>
<% end %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_customer_return_list), spree.admin_order_customer_returns_url(@order), :icon => 'arrow-left' %></li>
<% end %>

<% if @manual_intervention_return_items.any? %>
  <fieldset data-hook="manual_intervention_return_items" class="no-border-bottom">
    <legend align="center"><%= Spree.t(:manual_intervention_required) %></legend>
    <%= render partial: 'return_item_decision', locals: {return_items: @manual_intervention_return_items, show_decision: true} %>
  </fieldset>
<% end %>

<% if @pending_return_items.any? %>
  <fieldset data-hook="pending_return_items" class="no-border-bottom">
    <legend align="center"><%= Spree.t(:pending) %></legend>
    <%= render partial: 'return_item_decision', locals: {return_items: @pending_return_items, show_decision: true} %>
  </fieldset>
<% end %>

<% if @accepted_return_items.any? %>
  <fieldset data-hook="accepted_return_items" class="no-border-bottom">
    <legend align="center"><%= Spree.t(:accepted) %></legend>
    <%= render partial: 'return_item_decision', locals: {return_items: @accepted_return_items, show_decision: false} %>
  </fieldset>
<% end %>

<% if @rejected_return_items.any? %>
  <fieldset data-hook="rejected_return_items" class="no-border-bottom">
    <legend align="center"><%= Spree.t(:rejected) %></legend>
    <%= render partial: 'return_item_decision', locals: {return_items: @rejected_return_items, show_decision: false} %>
  </fieldset>
<% end %>

<% if !@customer_return.fully_reimbursed? && @pending_reimbursements.empty? %>
  <fieldset data-hook="reimbursements" class="no-border-bottom no-border-top align-center">
    <% if @customer_return.completely_decided? %>
      <%= form_for [:admin, @order, Spree::Reimbursement.new] do |f| %>
        <%= hidden_field_tag :build_from_customer_return_id, @customer_return.id %>
        <%= f.button class: 'button fa fa-reply' do %>
          <%= Spree.t(:create_reimbursement) %>
        <% end %>
      <% end %>
    <% else %>
      <div class="no-objects-found">
        <%= Spree.t(:unable_to_create_reimbursements) %>
      </div>
    <% end %>
  </fieldset>
<% end %>

<fieldset data-hook="reimbursements" class="no-border-bottom align-center">
  <legend align="center"><%= Spree::Reimbursement.model_name.human(count: :other) %></legend>
  <% if @customer_return.reimbursements.any? %>
    <%= render partial: 'reimbursements_table', locals: {reimbursements: @customer_return.reimbursements} %>
  <% else %>
    <div class="no-objects-found">
      <%= Spree.t(:none) %>
    </div>
  <% end %>
</fieldset>

solidus_backend-1.3.0/app/views/spree/admin/customer_returns/index.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Customer Returns' } %>

<% content_for :page_actions do %>
  <% if can? :create, Spree::CustomerReturn %>
    <li>
      <%= button_link_to Spree.t(:new_customer_return), spree.new_admin_order_customer_return_path(@order), icon: 'plus' %>
    </li>
  <% end %>
  <li><%= button_link_to Spree.t(:back_to_orders_list), spree.admin_orders_path, :icon => 'arrow-left' %></li>
<% end %>

<% content_for :page_title do %>
  <i class="fa fa-arrow-right"></i> <%= Spree::CustomerReturn.model_name.human(count: :other) %>
<% end %>

<% if @customer_returns.any? %>
  <table class="index">
    <thead data-hook="customer_return_header">
      <tr>
        <th><%= Spree::CustomerReturn.human_attribute_name(:number) %></th>
        <th><%= Spree::CustomerReturn.human_attribute_name(:pre_tax_total) %></th>
        <th><%= Spree::CustomerReturn.human_attribute_name(:total) %></th>
        <th><%= Spree::CustomerReturn.human_attribute_name(:created_at) %></th>
        <th><%= Spree::CustomerReturn.human_attribute_name(:reimbursement_status) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @customer_returns.each do |customer_return| %>
        <tr id="<%= spree_dom_id(customer_return) %>" data-hook="customer_return_row" class="<%= cycle('odd', 'even')%>">
          <td><%= link_to customer_return.number, edit_admin_order_customer_return_path(@order, customer_return) %></td>
          <td><%= customer_return.display_pre_tax_total.to_html %></td>
          <td><%= customer_return.display_total.to_html %></td>
          <td><%= pretty_time(customer_return.created_at) %></td>
          <td>
            <% if customer_return.fully_reimbursed? %>
              <span class="state success"><%= Spree.t(:reimbursed) %></span>
            <% else %>
              <span class="state notice"><%= Spree.t(:incomplete) %></span>
            <% end %>
          </td>
          <td class='actions align-center' data-hook="admin_orders_customer_returns_index_row_actions">
            <%= link_to_edit_url edit_admin_order_customer_return_path(@order, customer_return), title: "admin_edit_#{dom_id(customer_return)}", no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::CustomerReturn,
                 new_resource_url: new_object_url %>
  </div>
<% end %>

solidus_backend-1.3.0/app/views/spree/admin/customer_returns/new.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Customer Returns' } %>

<% content_for :page_title do %>
  <i class="fa fa-arrow-right"></i> <%= Spree.t(:new_customer_return) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_customer_return_list), spree.admin_order_customer_returns_url(@order), :icon => 'arrow-left' %></li>
<% end %>

<% if @rma_return_items.any? || @new_return_items.any? %>

  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @customer_return } %>
  <%= form_for [:admin, @order, @customer_return] do |f| %>
    <fieldset class="no-border-top">
      <div data-hook="admin_customer_return_form_fields">
        <fieldset class='no-border-bottom'>
          <legend align='center'><%= Spree.t(:items_in_rmas) %></legend>
          <% if @rma_return_items.any? %>
            <%= render partial: 'return_item_selection', locals: {f: f, return_items: @rma_return_items} %>
          <% else %>
            <div class="alpha twelve columns no-objects-found"><%= Spree.t(:none) %></div>
          <% end %>
        </fieldset>

        <fieldset class='no-border-bottom'>
          <legend align='center'><%= Spree.t(:other_items_in_other) %></legend>
          <% if @new_return_items.any? %>
            <%= render partial: 'return_item_selection', locals: {f: f, return_items: @new_return_items} %>
          <% else %>
            <div class="alpha twelve columns no-objects-found"><%= Spree.t(:none) %></div>
          <% end %>
        </fieldset>

        <%= f.field_container :stock_location do %>
          <%= f.label :stock_location_id, Spree::StockLocation.model_name.human %>
          <%= f.select :stock_location_id, Spree::StockLocation.order_default.to_a.collect{|l|[l.name.humanize, l.id]}, {include_blank: true}, {class: 'select2 fullwidth', "data-placeholder" => Spree.t(:select_a_stock_location)} %>
          <%= f.error_message_on :stock_location_id %>
        <% end %>

      </div>

      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t('actions.create'), 'ok' %>
        <%= button_link_to Spree.t('actions.cancel'), admin_order_customer_returns_url(@order), :icon => 'remove' %>
      </div>
    </fieldset>
  <% end %>

<% else %>

  <div class="twelve columns">
    <div class="alpha twelve columns no-objects-found">
      <%= Spree.t(:all_items_have_been_returned) %>,
      <%= link_to Spree.t(:back_to_customer_return_list), spree.admin_order_customer_returns_path(@order) %>.
    </div>
  </div>

<% end %>